# Week 00 - Elementary of PyTorch

In [54]:
import torch
import numpy as np

In [55]:
# Everything in PyTorch is based on Tensor operations.
# A tensor can have different dimensions: scalar, vector, matrix, tensor

# torch.empty(size): uninitialized
x = torch.empty(1)  # scalar
print("Scalar Tensor (uninitialized):")
print(x)
x = torch.empty(3)  # vector, 1D
print("\nVector Tensor (uninitialized):")
print(x)
x = torch.empty(2, 3)  # matrix, 2D
print("\nMatrix Tensor (uninitialized):")
print(x)
x = torch.empty(2, 2, 3)  # tensor, 3 dimensions
# x = torch.empty(2, 2, 2, 3)  # tensor, 4 dimensions
print("\nTensor (3D) Tensor (uninitialized):")
print(x)

Scalar Tensor (uninitialized):
tensor([0.])

Vector Tensor (uninitialized):
tensor([0., 0., 0.])

Matrix Tensor (uninitialized):
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor (3D) Tensor (uninitialized):
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [56]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print("\nRandom Tensor (Uniform Distribution):")
print(x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print("\nTensor Filled with Zeros:")
print(x)


Random Tensor (Uniform Distribution):
tensor([[0.8072, 0.0891, 0.7451],
        [0.5499, 0.1017, 0.5951],
        [0.5026, 0.4490, 0.4903],
        [0.3565, 0.3280, 0.3950],
        [0.0237, 0.7661, 0.0307]])

Tensor Filled with Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [57]:
# check size
print("\nSize of Tensor:")
print(x.size())

# check data type
print("\nData Type of Tensor:")
print(x.dtype)


Size of Tensor:
torch.Size([5, 3])

Data Type of Tensor:
torch.float32


In [58]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print("\nTensor with Specified Data Type (float16):")
print(x)

# check type
print("\nData Type of Tensor (after specifying):")
print(x.dtype)


Tensor with Specified Data Type (float16):
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

Data Type of Tensor (after specifying):
torch.float16


In [59]:
# construct from data
x = torch.tensor([5.5, 3])
print("\nTensor Constructed from Data:")
print(x.size())


Tensor Constructed from Data:
torch.Size([2])


In [60]:
# requires_grad argument
# This will tell PyTorch that it will need to calculate the gradients for this tensor
# later in your optimization steps
# i.e. this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
x

tensor([5.5000, 3.0000], requires_grad=True)

In [61]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

# elementwise addition
z = x + y
print("\nElement-wise Addition:")
print(z)

# in-place addition, everything with a trailing underscore is an inplace operation
# i.e. it will modify the variable
# y.add_(x)

# subtraction
z = x - y
print("\nSubtraction:")
print(z)

# multiplication
z = x * y
print("\nMultiplication:")
print(z)

# division
z = x / y
print("\nDivision:")
print(z)


Element-wise Addition:
tensor([[1.4420, 0.4001],
        [1.7059, 1.3165]])

Subtraction:
tensor([[ 0.3633, -0.0599],
        [-0.2216,  0.2659]])

Multiplication:
tensor([[0.4868, 0.0391],
        [0.7153, 0.4156]])

Division:
tensor([[1.6735, 0.7397],
        [0.7701, 1.5062]])


In [62]:
# Slicing
x = torch.rand(5, 3)
print("\nSliced Tensor:")
print(x)
print("\nSliced Column:")
print(x[:, 0])  # all rows, column 0
print("\nSliced Row:")
print(x[1, :])  # row 1, all columns
print("\nSingle Element:")
print(x[1, 1])  # element at 1, 1

# Get the actual value if only 1 element in your tensor
print("\nValue of Single Element:")
print(x[1, 1].item())


Sliced Tensor:
tensor([[0.6709, 0.8416, 0.5045],
        [0.6600, 0.6023, 0.0870],
        [0.2365, 0.3301, 0.1092],
        [0.7285, 0.9771, 0.3402],
        [0.1510, 0.2778, 0.5790]])

Sliced Column:
tensor([0.6709, 0.6600, 0.2365, 0.7285, 0.1510])

Sliced Row:
tensor([0.6600, 0.6023, 0.0870])

Single Element:
tensor(0.6023)

Value of Single Element:
0.6023251414299011


In [63]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1, PyTorch will automatically determine the necessary size
print("\nReshaping Tensors:")
print(x.size(), y.size(), z.size())


Reshaping Tensors:
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [64]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print("\nTensor Converted to NumPy Array:")
print(a)

# torch to numpy with .numpy()
b = a.numpy()
print("\nNumPy Array:")
print(b)
print("\nType of Converted Array:")
print(type(b))


Tensor Converted to NumPy Array:
tensor([1., 1., 1., 1., 1.])

NumPy Array:
[1. 1. 1. 1. 1.]

Type of Converted Array:
<class 'numpy.ndarray'>


In [65]:
# Careful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print("\nModified Tensor (after adding 1):")
print(a)
print("\nCorresponding NumPy Array (also modified):")
print(b)

# numpy to torch with .from_numpy(x)
a = np.ones(5)
b = torch.from_numpy(a)
print("\nNumPy Array Converted to Tensor:")
print(a)
print(b)

# again be careful when modifying
a += 1
print("\nModified NumPy Array (after adding 1):")
print(a)
print("\nCorresponding Tensor (also modified):")
print(b)


Modified Tensor (after adding 1):
tensor([2., 2., 2., 2., 2.])

Corresponding NumPy Array (also modified):
[2. 2. 2. 2. 2.]

NumPy Array Converted to Tensor:
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

Modified NumPy Array (after adding 1):
[2. 2. 2. 2. 2.]

Corresponding Tensor (also modified):
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [66]:
# by default all tensors are created on the CPU,
# but you can also move them to the GPU (only if it's available)
if torch.cuda.is_available():
    device = torch.device("cuda")  # a CUDA device object
    print(device)
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)  # or just use strings ``.to("cuda")``
    z = x + y
    print("\nTensor on GPU:")
    print(z)
    # move to CPU again
    z.to("cpu")  # ``.to`` can also change dtype together!
    print("\nTensor on CPU:")
    print(z)


In [67]:
# Check cuda or apple silicon
print(torch.cuda.is_available())
print(torch.backends.mps.is_available())

False
True
